os: Visual Studio 2015

platform:
  - Windows (32 Bit)
  - Windows (64 Bit)

configuration:
  - Shipping

before_build:
  # Xamarin targets spam up the log with a bunch of verbose messages, we don't care about these for MicroBuild,
  # so lets just get rid of them
  # http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - cd Build
  - cd Automation
  - cd Windows
  - GenerateBootstrap.bat
  - cd ..
  - cd ..
  - cd ..

build:
  project: Build\ProjectFiles\MicroBuild.sln
  verbosity: minimal
  
on_success: 
  - git config --global user.email "buildserver@programmingbytim.com"
  - git config --global user.name "Build Server"
  - cd Build
  - cd Automation
  - cd Windows
  - ps: if ($env:PLATFORM -eq "Windows (64 Bit)") { ./GitAddArtifacts_x64.bat }
  - ps: if ($env:PLATFORM -eq "Windows (32 Bit)") { ./GitAddArtifacts_x86.bat }
  - cd ..
  - cd ..
  - cd ..
  - git checkout %APPVEYOR_REPO_BRANCH%
  - git pull --no-edit --no-commit
  - git commit -m "[ci skip] Automated Build (Appveyor build %APPVEYOR_BUILD_NUMBER%)."
  - git push "https://TLeonardUK:%GITHUB_TOKEN%@github.com/TwinDrills/MicroBuild.git" --all --quiet
