os: Visual Studio 2017

platform:
  - x86/x64

configuration:
  - Shipping

install:
  - cmd: "CALL \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\VsDevCmd.bat\""

before_build:
  # Xamarin targets spam up the log with a bunch of verbose messages, we don't care about these for MicroBuild,
  # so lets just get rid of them
  # http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"  
  - if [%APPVEYOR_REPO_TAG%]==[false] (set MB_BUILD_VERSION=99.99) else (set MB_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%)    
  - 7z a -bb3 -tzip -r MicroBuild-Windows-%MB_BUILD_VERSION%.zip .\Build\ .\Docs\ .\Plugins\ .\Source\ .\Tests\ .\LICENCE.md .\README.md

build_script:  
  - cd ./Build
  - ./Build.Windows.bat
  - cd ..
  
after_build:
  - 7z a -bb3 -tzip -r MicroBuild-Windows-%MB_BUILD_VERSION%.zip Binaries\Windows\Shipping_x64\*
  - 7z a -bb3 -tzip -r MicroBuild-Windows-%MB_BUILD_VERSION%.zip Binaries\Windows\Shipping_x86\*

artifacts:
  - path: MicroBuild-Windows-$(MB_BUILD_VERSION).zip
    name: MicroBuild Windows 
  
deploy:
  release: MicroBuild $(MB_BUILD_VERSION)
  description: "Release of version $(MB_BUILD_VERSION) of MicroBuild."
  name: MicroBuild $MB_BUILD_VERSION
  tag: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: tYqB8BBM1Na+XEZm115VA8DZe1SQt3btU/AsTfAutYyCQ+p3MYY3f4u+c0AvmP6X
  artifact: MicroBuild-Windows-$(MB_BUILD_VERSION).zip
  on:
    appveyor_repo_tag: true
    
