os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Shipping

before_build:
  - cd Build
  - Generate.Windows.bat
  - cd ..

build:
  project: Build\ProjectFiles\MicroBuild.sln

on_success: 
  - ps: if ($env:PLATFORM -eq "x64")   { cp ./Binaries/MicroBuild_Windows_x64_Shipping.exe ./Binaries/windows_x64/microbuild.exe }
  - ps: if ($env:PLATFORM -eq "Win32") { cp ./Binaries/MicroBuild_Windows_x86_Shipping.exe ./Binaries/windows_x86/microbuild.exe }
  - git remote set-url origin "https://TLeonardUK:$GITHUB_TOKEN@github.com/TLeonardUK/MicroBuild.git"
  - git config --global user.email "buildserver@programmingbytim.com"
  - git config --global user.name "Build Server"
  - ps: if ($env:PLATFORM -eq "x64")   { git add ./Binaries/windows_x64/microbuild.exe }
  - ps: if ($env:PLATFORM -eq "Win32") { git add ./Binaries/windows_x86/microbuild.exe }
  - git commit -m "[ci skip] Automated Build (Appveyor build %APPVEYOR_BUILD_NUMBER%)."
  - git push
