language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r
    packages:
      - libstdc++-3.4
script: 
  - cd ./Build/
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
  - ./Generate.Linux.sh
  - cd ./ProjectFiles
  - make config=Shipping_x64

