language: cpp
compiler:
  - gcc
sudo: required
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
script: 
  - cd ./Build/
  - ./Generate.Linux.sh
  - cd ./ProjectFiles
  - make config=Shipping_x64

