language: cpp
osx_image: xcode8
os:
  - linux
  - osx
branches:
  only:
  - master
compiler:
  - gcc
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - gcc-multilib
    - g++-multilib
    - gcc-6-multilib
    - g++-6-multilib	
    - linux-libc-dev
script: 
  - cd ./Build/
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./Build.Linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./Build.MacOS.sh; fi
  - cd ./../
after_success: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 7z a MicroBuild-x64-v$(TRAVIS_BUILD_NUMBER).zip Binaries\Linux\Shipping_x64\*; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 7z a MicroBuild-x86-v$(TRAVIS_BUILD_NUMBER).zip Binaries\Linux\Shipping_x86\*; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then 7z a MicroBuild-x64-v$(TRAVIS_BUILD_NUMBER).zip Binaries\MacOS\Shipping_x64\*; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then 7z a MicroBuild-x86-v$(TRAVIS_BUILD_NUMBER).zip Binaries\MacOS\Shipping_x86\*; fi
deploy:
  provider: releases
  api_key: 
    secure: $GITHUB_TOKEN
  file: 
    - MicroBuild-x64-v$(TRAVIS_BUILD_NUMBER).zip 
    - MicroBuild-x86-v$(TRAVIS_BUILD_NUMBER).zip 
  skip_cleanup: true
  on:
    tags: true